### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yoppytaro** [yoppytaro/chat-space#7]
#IPアドレス
3.114.63.37

**Comment by kohei-isoda** [comment]
高田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◯ ヘッダーのグループ名が固定になってしまっている**
[![Screenshot from Gyazo](https://gyazo.com/444d9e55401dcd4e4be8b1ebabfe9e7c/raw)](https://gyazo.com/444d9e55401dcd4e4be8b1ebabfe9e7c)

**◯ メッセージ投稿画面右上にあるEditボタンを押すと新規グループ作成画面に遷移してしまう**
`※ 本来であればグループ編集画面に遷移しなければなりません。`

**◯ 自動更新で最新のメッセージが一定時間ごとに（何もしていないのに）増え続けてしまう**
[![Screenshot from Gyazo](https://gyazo.com/2d44e210ff28dfcf241891c86e724429/raw)](https://gyazo.com/2d44e210ff28dfcf241891c86e724429)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
